### ISSUE TITLE
Syntax error when trying to run 'pogo list'

### ISSUE THREAD

**Issue by giggsey** [Edznux/hubot-pokemongo#4]
> [Thu Jul 28 2016 08:53:51 GMT+0100 (BST)] ERROR TypeError: Cannot read property 'match' of undefined
>   at TextListener.callback (/hubot/node_modules/hubot-pokemongo/pokemongo.js:57:25)
>   at executeListener (/hubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
>   at allDone (/hubot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
>   at /hubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
>   at Object.async.eachSeries (/hubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
>   at Object.async.reduce (/hubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
>   at /hubot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
>   at process._tickCallback (node.js:355:11)

Running 1.1.0

**Comment by Edznux** [comment]
Oh my bad.
Should be fixed in 1.1.1.
Thanks !

**Comment by giggsey** [comment]
Still not working:

> [Thu Jul 28 2016 11:54:50 GMT+0100 (BST)] DEBUG Received message: 'hubot pogo help' in channel: DM, from: josh
> [Thu Jul 28 2016 11:54:50 GMT+0100 (BST)] DEBUG Message 'hubot pogo help' matched regex //(?:pogo)( .*)?/i/; listener.options = { id: null }
> [Thu Jul 28 2016 11:54:50 GMT+0100 (BST)] DEBUG Executing listener callback for Message 'hubot pogo help'
> [Thu Jul 28 2016 11:54:50 GMT+0100 (BST)] ERROR TypeError: Cannot read property 'match' of undefined
>   at TextListener.callback (/hubot/node_modules/hubot-pokemongo/pokemongo.js:57:25)
>   at executeListener (/hubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
>   at allDone (/hubot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
>   at /hubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
>   at Object.async.eachSeries (/hubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
>   at Object.async.reduce (/hubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
>   at /hubot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
>   at process._tickCallback (node.js:355:11)

**Comment by Edznux** [comment]
Which adapter do you use?
It seems it doesn't provide the "rawText" on res.message

**Comment by giggsey** [comment]
https://github.com/slackhq/hubot-slack at v4.0.1

**Comment by Edznux** [comment]
Ok thanks, we are running the v3.4.2 and it's working well, i'm actually in the process of updating this but there is some API changes in the version 4 (like the rawText removed).
Mostly done but can't figure out some DM problem atm.

**Comment by Edznux** [comment]
I've open an issue on the hubot-slack github.
It seems hubot cannot self open DM channel in v4.0.1

The only workaround at the moment is to set hubot-slack version to 3.4.2.

Is this a possibility for you?
If that's not, the main issue is that the bot won't send you direct message.
You could replace the "user.user" in `robot.messageRoom(user.user,msg);` to a public channel ID instead if you really want to but i won't push that in a public release.

**Comment by giggsey** [comment]
Okay, thanks.

I'll make the manual change locally to post to a public channel.

**Comment by Edznux** [comment]
If needed push the channel id into an object with the "room" property.
like : `robot.messageRoom({room:"C0QDQSQS"} ,msg);`
